#version: '3.8'

networks:
  backend:
    driver: bridge

services:
#  redis:
#    image: redis:latest
#    networks:
#      - backend
#    container_name: redis
#    ports:
#      - "6379:6379"
#  db:
#    image: mysql:8.0
#    container_name: mysql-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: fantasyshop
#      MYSQL_USER: fantasyshop
#      MYSQL_PASSWORD: fantasyshop
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
#    depends_on:
#      - redis
##      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    command: ["java", "-jar", "/app.jar"]
    networks:
      - backend

#volumes:
#  mysql-data:
